source "https://rubygems.org"

# use local theme gem for testing
gem "minimal-mistakes-jekyll", path: "../"
group :jekyll_plugins do
  gem 'jekyll-algolia', '~> 1.0'
end

gem "webrick"
gem "jekyll", "~> 3.5"